"""A deterministic single-agent Gymnasium adapter for the event simulator.

The controlled participant is an execution agent with a deliberately small
action space.  Heuristic agents continue to provide background liquidity.  A
step is considered complete only after the action has been submitted and the
next market-data barrier has been delivered, so fills generated by the action
are visible in the returned reward and observation.
"""

from __future__ import annotations

from dataclasses import asdict, replace
from math import isfinite
from typing import Any

import gymnasium
import numpy as np
from gymnasium import spaces

from app.agents.base import HeuristicAgent
from app.core.constants import TICK_SIZE, round_to_tick
from app.core.runner import BaselineScenario, DEFAULT_BASELINE_SCENARIO, SimulationRunner


class RLMarketAgent(HeuristicAgent):
    """Proxy between a Gym policy and the asynchronous market kernel."""

    N_OBS = 8
    ACTION_NAMES = ("HOLD", "BUY_LIMIT", "SELL_LIMIT", "BUY_MARKET", "SELL_MARKET")

    def __init__(
        self,
        agent_id: int,
        exchange_id: int,
        *,
        wake_interval: int = 20,
        start_price: float = 100.0,
        position_limit: int = 100,
        price_scale: float = 100.0,
        reward_scale: float = 100.0,
    ):
        super().__init__(
            agent_id,
            "RL_AGENT",
            initial_cash=0.0,
            position_limit=position_limit,
            allow_short=True,
        )
        if wake_interval <= 0:
            raise ValueError("wake_interval must be positive")
        if position_limit <= 0:
            raise ValueError("position_limit must be positive")
        if not isfinite(float(start_price)) or start_price <= 0:
            raise ValueError("start_price must be finite and positive")
        if price_scale <= 0 or reward_scale <= 0:
            raise ValueError("price_scale and reward_scale must be positive")
        self.exchange_id = exchange_id
        self.wake_interval = int(wake_interval)
        self.start_price = float(start_price)
        self.price_scale = float(price_scale)
        self.reward_scale = float(reward_scale)
        self.pending_action: tuple[int, int, int] | None = None
        self.observation_ready = False
        self._settlement_pending = False
        self._last_mkt: dict[str, float | None] = {
            "best_bid": None,
            "best_ask": None,
            "last_trade": self.start_price,
        }
        self._last_equity: float | None = None
        self._last_reward = 0.0
        self.last_action: tuple[int, int, int] | None = None
        self.last_action_status = "RESET"

    def reset(self) -> None:
        super().reset()
        self.pending_action = None
        self.observation_ready = False
        self._settlement_pending = False
        self._last_mkt = {
            "best_bid": None,
            "best_ask": None,
            "last_trade": self.start_price,
        }
        self._last_equity = None
        self._last_reward = 0.0
        self.last_action = None
        self.last_action_status = "RESET"

    def _market_values(self) -> tuple[float, float, float, float]:
        last = float(self._last_mkt.get("last_trade") or self.start_price)
        best_bid = float(self._last_mkt.get("best_bid") or last)
        best_ask = float(self._last_mkt.get("best_ask") or last)
        if best_bid <= 0 or best_ask <= 0:
            best_bid = best_ask = last
        mid = (best_bid + best_ask) / 2.0
        return best_bid, best_ask, best_ask - best_bid, mid

    def get_observation(self) -> np.ndarray:
        """Return eight bounded float32 features in ``[-1, 1]``."""

        best_bid, best_ask, spread, mid = self._market_values()
        last = float(self._last_mkt.get("last_trade") or self.start_price)
        position_limit = float(self.position_limit or 1)
        marked_pnl = self.compute_pnl(mid)
        values = np.asarray(
            [
                (best_bid - self.start_price) / self.price_scale,
                (best_ask - self.start_price) / self.price_scale,
                spread / 10.0,
                (mid - self.start_price) / self.price_scale,
                self.position / position_limit,
                marked_pnl / self.reward_scale,
                ((self.vwap or self.start_price) - self.start_price) / self.price_scale,
                (last - self.start_price) / self.price_scale,
            ],
            dtype=np.float32,
        )
        return np.clip(values, -1.0, 1.0)

    def get_reward(self) -> float:
        return float(self._last_reward)

    def wakeup(self, now: int) -> None:
        assert self.kernel is not None
        if self.state == "AWAITING_DATA":
            return
        self.state = "AWAITING_DATA"
        self.kernel.send(self.agent_id, self.exchange_id, "QUERY_MKT_DATA", {})

    def receive(self, msg) -> None:
        if msg.kind == "MKT_DATA" and self.state == "AWAITING_DATA":
            self.state = "ACTIVE"
            self._last_mkt = {
                "best_bid": msg.data.get("best_bid"),
                "best_ask": msg.data.get("best_ask"),
                "last_trade": msg.data.get("last_trade", self.start_price),
            }
            action_was_submitted = self.pending_action is not None
            if action_was_submitted:
                action = self.pending_action
                self.pending_action = None
                assert action is not None
                self.last_action = action
                self._execute_action(*action)
                self._settlement_pending = True
                self.observation_ready = False
            else:
                self.observation_ready = True

            if self._settlement_pending and not action_was_submitted:
                self._settlement_pending = False
                self._update_reward()
                self.observation_ready = True

            self.kernel.wakeup(self.agent_id, self.kernel.time + self.wake_interval)
        elif msg.kind == "EXECUTION":
            self.handle_execution(msg)
        elif msg.kind == "ORDER_ACCEPTED":
            self.handle_order_accepted(msg)
        elif msg.kind == "ORDER_CANCELLED":
            self.handle_order_cancelled(msg)
        elif msg.kind == "ORDER_REJECTED":
            self.last_action_status = str(msg.data.get("reason", "REJECTED"))

    def _update_reward(self) -> None:
        _, _, _, mid = self._market_values()
        equity = self.marked_equity(mid)
        if self._last_equity is None:
            self._last_reward = 0.0
        else:
            self._last_reward = float(np.clip((equity - self._last_equity) / self.reward_scale, -10.0, 10.0))
        self._last_equity = equity
        self.pnl_history.append(equity - self.initial_cash)

    def _execute_action(self, action_type: int, price_ticks: int, qty_bin: int) -> None:
        if action_type not in range(len(self.ACTION_NAMES)):
            raise ValueError(f"invalid action type {action_type}")
        if price_ticks < 0 or price_ticks >= 20:
            raise ValueError(f"invalid price tick offset {price_ticks}")
        if qty_bin < 0 or qty_bin >= 10:
            raise ValueError(f"invalid quantity bin {qty_bin}")

        qty = qty_bin + 1
        _, _, _, mid = self._market_values()
        offset = price_ticks * TICK_SIZE
        self.last_action_status = "HOLD" if action_type == 0 else "SUBMITTED"
        if action_type == 0:
            return
        if action_type == 1:
            order = {"order_type": "LIMIT", "side": "BUY", "qty": qty, "price": round_to_tick(mid - offset)}
        elif action_type == 2:
            order = {"order_type": "LIMIT", "side": "SELL", "qty": qty, "price": round_to_tick(mid + offset)}
        elif action_type == 3:
            order = {"order_type": "MARKET", "side": "BUY", "qty": qty}
        else:
            order = {"order_type": "MARKET", "side": "SELL", "qty": qty}
        self.kernel.send(self.agent_id, self.exchange_id, "NEW_ORDER", order)


class AbidesGymEnv(gymnasium.Env):
    """Gymnasium environment with one controlled execution agent."""

    metadata = {"render_modes": []}
    RL_AGENT_ID = 100

    def __init__(
        self,
        seed: int = 42,
        max_steps: int = 500,
        rl_step_interval: int = 20,
        scenario: BaselineScenario | None = None,
        position_limit: int = 100,
    ):
        if not isinstance(max_steps, int) or isinstance(max_steps, bool) or max_steps <= 0:
            raise ValueError("max_steps must be a positive integer")
        if not isinstance(rl_step_interval, int) or isinstance(rl_step_interval, bool) or rl_step_interval <= 0:
            raise ValueError("rl_step_interval must be a positive integer")
        if position_limit <= 0:
            raise ValueError("position_limit must be positive")
        self._seed = int(seed)
        self.max_steps = max_steps
        self.rl_step_interval = rl_step_interval
        self.position_limit = position_limit
        self.scenario = scenario or DEFAULT_BASELINE_SCENARIO
        self.observation_space = spaces.Box(
            low=-1.0,
            high=1.0,
            shape=(RLMarketAgent.N_OBS,),
            dtype=np.float32,
        )
        self.action_space = spaces.MultiDiscrete(np.asarray([5, 20, 10], dtype=np.int64))
        self._runner = SimulationRunner(scenario=self.scenario)
        self._rl_agent: RLMarketAgent | None = None
        self._steps = 0
        self._terminated = False
        self._truncated = False
        self._closed = False

    @property
    def runner(self) -> SimulationRunner:
        """Expose the runner for read-only experiment diagnostics."""

        return self._runner

    def reset(self, *, seed: int | None = None, options: dict | None = None):
        del options
        super().reset(seed=seed)
        if seed is not None:
            self._seed = int(seed)
        self.scenario = replace(self.scenario, seed=self._seed)
        self._runner.reset(seed=self._seed, scenario=self.scenario)
        self._rl_agent = RLMarketAgent(
            self.RL_AGENT_ID,
            0,
            wake_interval=self.rl_step_interval,
            start_price=self.scenario.start_price,
            position_limit=self.position_limit,
        )
        self._runner.register_agent(self._rl_agent, first_wakeup=1)
        self._steps = 0
        self._terminated = False
        self._truncated = False
        self._closed = False
        self._advance_to_next_observation()
        if not self._rl_agent.observation_ready:
            self._terminated = True
            raise RuntimeError("simulation ended before the initial observation")
        observation = self._rl_agent.get_observation()
        info = self._info()
        info["seed"] = self._seed
        info["scenario"] = asdict(self.scenario)
        return observation, info

    def step(self, action):
        if self._closed:
            raise RuntimeError("environment is closed")
        if self._rl_agent is None:
            raise RuntimeError("call reset() before step()")
        if self._terminated or self._truncated:
            raise RuntimeError("episode is finished; call reset() before step()")
        candidate = np.asarray(action)
        if not self.action_space.contains(candidate):
            raise ValueError(f"action is outside {self.action_space}: {action!r}")
        self._rl_agent.pending_action = tuple(int(value) for value in candidate.tolist())
        self._advance_to_next_observation()
        self._steps += 1
        self._terminated = not self._runner.kernel.running or not self._rl_agent.observation_ready
        self._truncated = self._steps >= self.max_steps and not self._terminated
        if self._terminated or self._truncated:
            self._runner.stop()
        info = self._info()
        info["action"] = list(self._rl_agent.last_action or ())
        info["action_status"] = self._rl_agent.last_action_status
        info["steps"] = self._steps
        if self._terminated:
            info["termination_reason"] = "simulation_exhausted"
        elif self._truncated:
            info["termination_reason"] = "max_steps"
        return (
            self._rl_agent.get_observation(),
            self._rl_agent.get_reward(),
            self._terminated,
            self._truncated,
            info,
        )

    def render(self):
        return self._runner.get_state()

    def close(self):
        if self._runner.kernel and self._runner.kernel.running:
            self._runner.stop()
        self._closed = True

    def _info(self) -> dict[str, Any]:
        if self._rl_agent is None or self._runner.kernel is None:
            return {}
        best_bid, best_ask, spread, mid = self._rl_agent._market_values()
        return {
            "sim_time": self._runner.kernel.time,
            "position": self._rl_agent.position,
            "cash": round(self._rl_agent.cash, 8),
            "realized_pnl": round(self._rl_agent.realized_pnl, 8),
            "marked_pnl": round(self._rl_agent.compute_pnl(mid), 8),
            "active_orders": len(self._rl_agent.active_orders),
            "best_bid": best_bid,
            "best_ask": best_ask,
            "spread": spread,
            "last_trade": float(self._rl_agent._last_mkt.get("last_trade") or mid),
            "market_volume": self._runner.exchange.total_traded_qty if self._runner.exchange else 0,
        }

    def _advance_to_next_observation(self) -> None:
        if self._rl_agent is None or self._runner.kernel is None:
            return
        self._rl_agent.observation_ready = False
        while self._runner.kernel.running and not self._rl_agent.observation_ready:
            if not self._runner.kernel.has_events:
                self._runner.kernel.running = False
                break
            self._runner.step()
